export default {
  account: "Account",
  signout: "Logout",
  error: "Error",
  employee: "Employee",
  employees: "Employees",
  newEmployee: "New Employee",
  save: "Save",
  total: "Total",
  totals: "Totals",
  id: "ID",
  name: "Name",
  surname: "Surname",
  workedHours: "Worked Hours",
  hourly: "Hourly",
  hourlySalaryOf: "The hourly salary of",
  isDifferentthatCurrent: "is different than the current one",
  hourlySalary: "Hourly Salary",
  selectEmployee: "Select an Employee",
  tracking: "Tracking",
  deletedHour: "Deleted Hour",
  deletedHourSuccess: "Hour deleted successfully",
  savedHour: "Hour saved",
  savedHourSuccess: "Hour saved successfully",
  deleteHour: "Delete Hour",
  deleteConfirm: "Confirm to remove",
  deleteEmployee: "Delete Employee",
  deletedEmployee: "Deleted Employee",
  deletedEmployeeConfirm: "Emoployee deleted successfully",
  savedEmployee: "Saved Emoployee",
  savedEmployeeConfirm: "Emoployee saved successfully",
  cancel: "Cancel",
  ok: "OK",
  login: "Login",
  signupLink: "Don't have an account? Sign Up",
  emailPlaceholder: "Email",
  emailRequired: "Email is required",
  emailWrong: "Email is wrong",
  passwordPlaceholder: "Password",
  passwordRequired: "Password is required",
  agenda: "Agenda",
  fillData: "Fill the information",
  delete: "Delete"
};
