export default {
  account: "Account",
  signout: "Logout",
  error: "Errore",
  employee: "Dipendente",
  employees: "Dipendenti",
  newEmployee: "Nuovo Dipendente",
  save: "Salva",
  total: "Totale",
  totals: "Totali",
  id: "ID",
  name: "Nome",
  surname: "Cognome",
  workedHours: "Ore Lavorate",
  hourly: "all'ora",
  hourlySalaryOf: "Lo stipendio orario di",
  hourlySalary: "Stipendio orario",
  isDifferentthatCurrent: "è diverso da quello attuale",
  selectEmployee: "Seleziona un Dipendente",
  tracking: "Tracciamento",
  deletedHour: "Ora eliminata",
  deletedHourSuccess: "L'ora è stata eliminata con successo",
  savedHour: "Ora salvata",
  savedHourSuccess: "L'ora è stata salvata con successo",
  deleteHour: "Elimina ora",
  deleteConfirm: "Confermi di voler eliminare",
  deleteEmployee: "Elimina Dipendente",
  deletedEmployee: "Dipendente eliminato",
  deletedEmployeeConfirm: "Il Dipendente è stata eliminato con successo",
  savedEmployee: "Dipendente salvato",
  savedEmployeeConfirm: "Il Dipendente è stata salvata con successo",
  cancel: "Annulla",
  ok: "OK",
  login: "Login",
  signupLink: "Non hai un account? Registrati",
  emailPlaceholder: "Email",
  emailRequired: "L'email è obbligatoria",
  emailWrong: "L'email non è corretta",
  passwordPlaceholder: "Password",
  passwordRequired: "La password è obbligatoria",
  agenda: "Agenda",
  fillData: "Compila le informazioni",
  delete: "Elimina"
};
